### ISSUE TITLE
Detected Trojan

### ISSUE THREAD

**Issue by cpmcgrath** [OliverKohlDSc/Terminals#16]
Hi,
I'm not sure if this is a false positive or not, but I installed using Setup_4.9.0.0.exe and Windows Defender immediately quarantined it as  Trojan:Win32/Rundas!plock

I'm using Windows 10 x64 (Up to date)

![terminalstrojan](https://cloud.githubusercontent.com/assets/1791243/18186670/5b791fee-70e7-11e6-8994-4f05b960ad5d.png)

https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fRundas!plock&threatid=2147711527&enterprise=0

**Comment by OliverKohlDSc** [comment]
Dear @cpmcgrath,

that's a false positive.

Anyway I've created a new setup where I've removed the packing and compressing steps for the binaries like upx packing (which sometimes gets reported as malicious or malware, due to the fact that a lot of fraud people are using these packers for cracks or "patches".)

Is it working for you with this release?
https://github.com/OliverKohlDSc/Terminals/releases/download/4.9.1.0/Setup_Terminals.exe

Thanks

Oliver

**Comment by OliverKohlDSc** [comment]
Dear @cpmcgrath,

I've tested it on a virtual machine and the problem seems to be gone.

Thanks
Oliver
