### ISSUE TITLE
Menu and toolbar reappear after closing the last connection

### ISSUE THREAD

**Issue by curpin** [OliverKohlDSc/Terminals#31]
If I hide the toolbar and the menu and then make an RDP connection.
When I close the RDP connection, the toolbar and the menu reappear.

**Comment by OliverKohlDSc** [comment]
I've create a new tag with a new testing release [4.9.2.0](https://github.com/OliverKohlDSc/Terminals/releases/tag/4.9.2.0).

Closing the last connection in the Terminals full screen state reverts the full screen back to the normal mode. i.e. Terminals will now show the priviously hidden toolbars. To prevent this "feature", which in my opineon works as designed a new setting in the Terminals options has been implemented, which can now be set to false. (LetTerminalsAutomaticallyManageRevertFromFullScreenMode := true)

By setting the option/setting can you confirm that the problem is solved for you?

Regards

Oliver

**Comment by curpin** [comment]
yes, It looks like working now.  Thank you.
